name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          echo "VITE_API_URL=https://draftbash.azurewebsites.net/api/v1" > .env
          echo "VITE_SERVER_URL=https://draftbash.azurewebsites.net" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DRAFT_BASH }}
          channelId: live
          projectId: draft-bash